digit        <- '0' / '1' / '2' / '3' / '4' / '5' / '6' / '7' / '8' / '9'
              ;
hex_digit    <- digit / 'a' / 'b' / 'c' / 'd' / 'e' / 'f' / 'A' / 'B' / 'C' / 'D' / 'E' / 'F'
              ;
lower_letter <- 'a' / 'b' / 'c' / 'd' / 'e' / 'f' / 'g' / 'h' / 'i' / 'j' / 'k' / 'l' / 'm' / 'n' / 'o' / 'p' / 'q' / 'r' / 's' / 't' / 'u' / 'v' / 'w' / 'x' / 'y' / 'z'
              ;
upper_letter <- 'A' / 'B' / 'C' / 'D' / 'E' / 'F' / 'G' / 'H' / 'I' / 'J' / 'K' / 'L' / 'M' / 'N' / 'O' / 'P' / 'Q' / 'R' / 'S' / 'T' / 'U' / 'V' / 'W' / 'X' / 'Y' / 'Z'
              ;
letter       <- lower_letter / upper_letter
              ;
space        <- ' ' / '\t' / '\r' / '\n'
              ;
_            <- space*
              ;
ident        <- letter (letter / digit / '_')*
              ;
