digits        <- '0' / '1' / '2' / '3' / '4' / '5' / '6' / '7' / '8' / '9'
               ;
hex_digits    <- digits / 'a' / 'b' / 'c' / 'd' / 'e' / 'f' / 'A' / 'B' / 'C' / 'D' / 'E' / 'F'
               ;
lower_letters <- 'a' / 'b' / 'c' / 'd' / 'e' / 'f' / 'g' / 'h' / 'i' / 'j' / 'k' / 'l' / 'm' / 'n' / 'o' / 'p' / 'q' / 'r' / 's' / 't' / 'u' / 'v' / 'w' / 'x' / 'y' / 'z'
               ;
upper_letters <- 'A' / 'B' / 'C' / 'D' / 'E' / 'F' / 'G' / 'H' / 'I' / 'J' / 'K' / 'L' / 'M' / 'N' / 'O' / 'P' / 'Q' / 'R' / 'S' / 'T' / 'U' / 'V' / 'W' / 'X' / 'Y' / 'Z'
               ;
letters       <- lower_letters / upper_letters
               ;
space         <- ' ' / '\t' / '\r' / '\n'
               ;
_             <- space*
               ;
ident         <- letters (letters / digits / '_')*
               ;
